# syntax = docker/dockerfile:1.0-experimental

FROM golang:1.16 AS documentation
WORKDIR /src/
COPY go.* /src/
COPY cmd/. /src/cmd/
COPY pkg/. /src/pkg/
RUN go mod download
RUN go get github.com/go-swagger/go-swagger/cmd/swagger
